### ISSUE TITLE
Facility to nominate an 'events page'

### ISSUE THREAD

**Issue by richplane** [castlegateit/cgit-wp-events#1]
PROPOSAL:
The plugin should have another option under 'Event Settings' which allows a site editor to nominate a page to host the event archives (in the same way as the Posts Page is nominated under 'Reading')

This has two effects:
1. It sets an option which can be used in the archive-events.php template to pull through content from the nominated page (for e.g. banner image, SEO etc)
2. It sets up a redirect from the nominated page to the archive-events.php template (probably using the [template_redirect](https://codex.wordpress.org/Plugin_API/Action_Reference/template_redirect) filter?) so we see that template on this page without any HTTP redirect

**Comment by johnkhughes** [comment]
I'm going to close this because we've moved on to a new version of the plugin.
